### ISSUE TITLE
Get appropriate NLDAS time along with associated x,y grid 

### ISSUE THREAD

**Issue by jzwart** [DOI-USGS/lake-temperature-process-models-old#10]
Right now, we grab the NLDAS x,y grid coords for each lake's driver data, but we also need the associated NLDAS_time (e.g. `0.350500` or `0.351500`). @jread-usgs how did you assign NLDAS_time when creating the drivers?

**Comment by jordansread** [comment]
The time range is an object target here: https://github.com/USGS-R/lake-temperature-model-prep/blob/master/6_drivers_fetch.yml#L24

So if you were linked to that remake file, you could call the target. Otherwise you could hardcode it, but put a comment in that links to this part of the driver build remake file.

**Comment by jordansread** [comment]
Times come from our use of `'../lake-temperature-model-prep/7_config_merge/out/nml_list.rds'` now
