### ISSUE TITLE
Fill in missing lake names in crosswalk

### ISSUE THREAD

**Issue by aappling-usgs** [DOI-USGS/lake-temperature-process-models-old#5]
There are some lakes in the file written in [these lines](https://github.com/USGS-R/lake-temperature-process-models/blob/6d79925cd642139d3797963654d04298ef61137b/1_get_lake_attr.yml#L39-L40) that have missing lake names. 

In pipeline 3 we've been filling in those missing names using a hand-written spreadsheet (missing_names_crosswalk in [this Drive folder](https://drive.google.com/drive/u/0/folders/1nRUG4R5rnc7TVOieG7PPXlyOIEJGLcpG)).

But it sure seems to me that filling in missing names would fit better conceptually in the pipeline that's creating the crosswalk rather than the pipeline that's using it...is that an option? @jzwart, @limnoliver ?

**Comment by limnoliver** [comment]
The reason the missing names are corrected in pipeline 3 is because the priority lakes are identified there, which drastically reduces the missing-name-space (e.g., there are a lot of missing lake names, but we only need to/want to correct the priority lakes). 

I agree that it would make more sense earlier in the pipeline, but I don't think it's logistically possible since this is a mostly manual process. Does that make sense?

**Comment by aappling-usgs** [comment]
Oh, I see. Yes, that makes sense. Thanks.
